### ISSUE TITLE
Mode Standalone / Erreur sauvegarde lors de la réservation d'une place

### ISSUE THREAD

**Issue by vwilliam** [lefevre00/parking#103]
Hibernate: update PLACES set EMAIL_OCCUPANT=? where (OCCUPATION_DATE, ID)=(?, ?)
[http-nio-8080-exec-8] ERROR spark.webserver.MatcherFilter -
org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [protected java.lang.String org.friends.app.model.Place$PlacePK.occupationDate] by reflection for persistent property [org.friends.app.model.Place$PlacePK#occupationDate] : Place [placeNumber=141, usedBy=null, occupationDate=2016-07-22]
        at org.hibernate.property.access.spi.GetterFieldImpl.get(GetterFieldImpl.java:71)
        at org.hibernate.tuple.component.AbstractComponentTuplizer.getPropertyValue(AbstractComponentTuplizer.java:58)
        at org.hibernate.tuple.component.AbstractComponentTuplizer.getPropertyValues(AbstractComponentTuplizer.java:64)
        at org.hibernate.tuple.component.PojoComponentTuplizer.getPropertyValues(PojoComponentTuplizer.java:95)
        at org.hibernate.type.ComponentType.getPropertyValues(ComponentType.java:438)
        at org.hibernate.type.ComponentType.nullSafeGetValues(ComponentType.java:379)
        at org.hibernate.type.ComponentType.nullSafeSet(ComponentType.java:332)
        at org.hibernate.param.NamedParameterSpecification.bind(NamedParameterSpecification.java:53)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:82)
        at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:59)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:429)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
        at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1471)
        at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1428)
        at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1406)
        at org.friends.app.dao.PlaceDao.update(PlaceDao.java:34)
        at org.friends.app.service.impl.PlaceServiceBean.book(PlaceServiceBean.java:109)
        at org.friends.app.view.route.BookRoute.doHandle(BookRoute.java:47)
        at org.friends.app.view.route.AuthenticatedRoute.handle(AuthenticatedRoute.java:26)
        at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:122)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.String field org.friends.app.model.Place$PlacePK.occupationDate to org.friends.app.model.Place
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source)
        at java.lang.reflect.Field.get(Unknown Source)
        at org.hibernate.property.access.spi.GetterFieldImpl.get(GetterFieldImpl.java:67)
        ... 39 more

**Comment by lefevre00** [comment]
Est-ce que la creation de compte marche en standalone ? (comme avec h2, en mode log console)

Pour savoir, si c'est insertion dans cette base, ou juste dans la table ?

**Comment by vwilliam** [comment]
L'insertion en base fonctionne en mode standalone. 
Mais j'ai l'impression que l'update ne fonctionne pas.
Dans notre cas c'est lorsque l'on veut modifier l'id de la place.
Le soucis est également présent sur mon tomcat local...

**Comment by lefevre00** [comment]
La clé étant id/date, une modif de l'id devrait impliquée un delete + insert ?

**Comment by vwilliam** [comment]
Nouveau message d'erreur suite à l'installation de la version standalone :

org.springframework.orm.hibernate5.HibernateSystemException: getNamedQuery is not valid without active transaction; nested exception is org.hibernate.HibernateException: getNamedQuery is not valid without active transaction
        at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:258)
        at org.springframework.orm.hibernate5.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:57)
        at org.springframework.orm.hibernate5.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:44)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at org.friends.app.dao.impl.UserSessionDaoImpl$$EnhancerBySpringCGLIB$$db73cfde.findByCookie(<generated>)
        at org.friends.app.service.impl.UserServiceBean.findUserByCookie(UserServiceBean.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy102.findUserByCookie(Unknown Source)
        at org.friends.app.view.route.AuthenticatedRoute.checkAuthenticated(AuthenticatedRoute.java:44)
        at org.friends.app.view.route.AuthenticatedRoute.handle(AuthenticatedRoute.java:25)
        at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.servlet.SparkFilter.doFilter(SparkFilter.java:122)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.HibernateException: getNamedQuery is not valid without active transaction
        at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:334)
        at com.sun.proxy.$Proxy103.getNamedQuery(Unknown Source)
        at org.friends.app.dao.impl.UserSessionDaoImpl.findByCookie(UserSessionDaoImpl.java:43)
        at org.friends.app.dao.impl.UserSessionDaoImpl$$FastClassBySpringCGLIB$$868a5ea9.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        ... 44 more
^C
