### ISSUE TITLE
Connection Postgres

### ISSUE THREAD

**Issue by lefevre00** [lefevre00/parking#92]
ERROR: FATAL: too many connections for role "mssbzhocnhzlzu" 
Jun 07 00:34:00 takemyplace app/web.1:  [qtp1091825220-46] ERROR spark.webserver.MatcherFilter -  
Jun 07 00:34:00 takemyplace app/web.1:  org.hibernate.exception.GenericJDBCException: Error calling Driver#connect 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.convertSqlException(BasicConnectionCreator.java:118) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:41) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:58) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.getConnection(DriverManagerConnectionProviderImpl.java:189) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:386) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:84) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:109) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:47) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1927) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1896) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1874) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.doQuery(Loader.java:919) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.doList(Loader.java:2610) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.doList(Loader.java:2593) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2422) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.Loader.list(Loader.java:2417) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:385) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.friends.app.dao.PlaceDao.findPlaceByCriterions(PlaceDao.java:88) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.friends.app.service.impl.PlaceServiceBean.isPlaceShared(PlaceServiceBean.java:219) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.friends.app.view.route.ShareRoute.doHandle(ShareRoute.java:42) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.friends.app.view.route.AuthenticatedRoute.handle(AuthenticatedRoute.java:26) 
Jun 07 00:34:00 takemyplace app/web.1:      at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66) 
Jun 07 00:34:00 takemyplace app/web.1:      at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) 
Jun 07 00:34:00 takemyplace app/web.1:      at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.Server.handle(Server.java:517) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) 
Jun 07 00:34:00 takemyplace app/web.1:      at java.lang.Thread.run(Thread.java:745) 
Jun 07 00:34:00 takemyplace app/web.1:  Caused by: org.postgresql.util.PSQLException: FATAL: too many connections for role "mssbzhocnhzlzu" 
Jun 07 00:34:00 takemyplace app/web.1:      at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:712) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:67) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.postgresql.Driver.makeConnection(Driver.java:406) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.postgresql.Driver.connect(Driver.java:274) 
Jun 07 00:34:00 takemyplace app/web.1:      at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:38) 
Jun 07 00:34:00 takemyplace app/web.1:      ... 44 more

**Comment by lefevre00** [comment]
Voir https://mestachs.wordpress.com/tag/hibernate/
