### ISSUE TITLE
Exception freemarker

### ISSUE THREAD

**Issue by lefevre00** [lefevre00/parking#95]
Jun 09 04:32:08 takemyplace heroku/router: at=info method=GET path="/user/logout" host=takemyplace.herokuapp.com request_id=07a80827-2a60-4591-8b1f-6d95ec2c7c2b fwd="193.105.26.130" dyno=web.1 connect=1ms service=4ms status=302 bytes=165 
Jun 09 04:32:08 takemyplace app/web.1: java.lang.NullPointerException 
Jun 09 04:32:08 takemyplace app/web.1:  at org.friends.app.view.route.AuthenticatedRoute.checkAuthenticated(AuthenticatedRoute.java:42) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.friends.app.view.route.AuthenticatedRoute.handle(AuthenticatedRoute.java:25) 
Jun 09 04:32:08 takemyplace app/web.1:  at spark.TemplateViewRouteImpl$1.handle(TemplateViewRouteImpl.java:66) 
Jun 09 04:32:08 takemyplace app/web.1:  at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162) 
Jun 09 04:32:08 takemyplace app/web.1:  at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.Server.handle(Server.java:517) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) 
Jun 09 04:32:08 takemyplace app/web.1:  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) 
Jun 09 04:32:08 takemyplace app/web.1:  at java.lang.Thread.run(Thread.java:745) 
Jun 09 04:32:08 takemyplace app/web.1: Jun 09, 2016 11:32:08 AM freemarker.log.JDK14LoggerFactory$JDK14Logger error 
Jun 09 04:32:08 takemyplace app/web.1: SEVERE: Template processing error: "Expression message is undefined on line 18, column 27 in error.ftl." 
Jun 09 04:32:08 takemyplace app/web.1: Expression message is undefined on line 18, column 27 in error.ftl. 
Jun 09 04:32:08 takemyplace app/web.1: The problematic instruction: 
Jun 09 04:32:08 takemyplace app/web.1: ---------- 
Jun 09 04:32:08 takemyplace app/web.1: ==> ${message} [on line 18, column 25 in error.ftl] 
Jun 09 04:32:08 takemyplace app/web.1: ---------- 
Jun 09 04:32:08 takemyplace app/web.1: Java backtrace for programmers: 
Jun 09 04:32:08 takemyplace app/web.1: ---------- 
Jun 09 04:32:08 takemyplace app/web.1: freemarker.core.InvalidReferenceException: Expression message is undefined on line 18, column 27 in error.ftl.

**Comment by lefevre00** [comment]
Reproductible lors du refresh sur la page logout
